version: '3.4'
services:
  app:
    build:
      context: docker
    volumes:
      - ./:/app:rw
      - ./gar_xml.zip:/fias_gar_xml/fias_gar_xml.zip:ro

  database:
    image: mysql:8.0.22
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: fias
      MYSQL_USER: alex
      MYSQL_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 1

  webserver:
    image: nginx:1.19.3-alpine
    ports:
      - "9999:80"
    depends_on:
      - app
    volumes:
      - ./:/app:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf